- source: screen
  enable: true
  type: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: screen
  debug: true
- source: hbkj
  enable: true
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  database: lightapps
  debug: true