- source: backup
  enable: true
  type: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: backup_server
  debug: true
- source: huawei
  enable: true
  type: postgres
  host: 1.94.7.42
  port: 8891
  username: postgres
  password: postgres
  database: screen
  debug: true
- source: nkdx
  enable: true
  type: postgres
  host: 192.168.2.248
  port: 5432
  username: postgres
  password: PPJbh9z7zrRrH9a4
  database: nkdx
  debug: true