app: quanchao_test_gen
frame: go-quanx
output: D:\Code\Go\src\github.com\go-xuan
tables:
db:
  type: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: screen
  debug: true
