app: nkdx_screen
frame: go-quanx
output: D:\Code\Go\src\github.com\go-xuan
db:
  type: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: screen
  schema: nkdx