app: quan_user
frame: go-quanx
#frame: go-frame
output: D:\Code\Go\src\qc_gen
tablePrefix: t_sys_
db:
  type: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: quan_user
  schema: public